# Generated by Django 5.1.6 on 2025-03-19 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الفئة')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('product_image', models.ImageField(upload_to='ProductsImages/%Y/%m/%d/', verbose_name='صورة المنتج')),
                ('product_purchas_cost', models.FloatField(verbose_name='سعر الشراء')),
                ('product_selling_price', models.FloatField(verbose_name='سعر البيع')),
                ('product_stock_quantity', models.IntegerField(verbose_name='الكمية في المخزون')),
                ('product_age_range', models.CharField(choices=[('a', '1-3 أشهر'), ('b', '3-4 أشهر'), ('c', '4-6 أشهر'), ('d', '6-9 أشهر'), ('e', '9-12 أشهر'), ('f', 'سنة'), ('g', 'لكل الأعمار')], max_length=50, verbose_name='الفئة العمرية')),
                ('product_gender', models.CharField(choices=[('a', 'ذكر'), ('b', 'أنثى'), ('c', 'للجنسين')], max_length=10, verbose_name='الجنس')),
                ('product_created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product_updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product_is_active', models.BooleanField(default=True, verbose_name='متاح')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductsImagesAdd/%Y/%m/%d/', verbose_name='الصورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='_product.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفئة الفرعية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.category', verbose_name='الفئة الرئيسية')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.subcategory', verbose_name='الفئة الفرعية'),
        ),
    ]
