# Generated by Django 5.1.6 on 2025-03-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0010_alter_customerbaby_baby_picture'),
        ('_product', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_age_range',
            field=models.CharField(choices=[('a', '1-3 أشهر'), ('b', '3-4 أشهر'), ('c', '4-6 أشهر'), ('d', '6-9 أشهر'), ('e', '9-12 أشهر'), ('f', 'سنة')], default='g', max_length=50, verbose_name='الفئة العمرية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('#FF0000', 'أحمر'), ('#0000FF', 'أزرق'), ('#FFFF00', 'أصفر'), ('#00FF00', 'أخضر'), ('#FFA500', 'برتقالي'), ('#800080', 'بنفسجي'), ('#000000', 'أسود'), ('#FFFFFF', 'أبيض'), ('#808080', 'رمادي'), ('#A52A2A', 'بني'), ('#FFC0CB', 'وردي'), ('#F5F5DC', 'بيج')], default='h', max_length=10, verbose_name='اللون'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_account.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
