# Generated by Django 5.1.6 on 2025-03-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0010_alter_customerbaby_baby_picture'),
        ('_product', '0004_alter_product_product_age_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'مفضل', 'verbose_name_plural': 'المفضلة'},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_account.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product', verbose_name='المنتج'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_account.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'السلة',
                'verbose_name_plural': 'السلل',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('total_price', models.FloatField(verbose_name='السعر الاجمالي')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.cart', verbose_name='العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصرالسلة',
                'verbose_name_plural': 'عناصر السلة',
            },
        ),
    ]
