# Generated by Django 5.1.6 on 2025-03-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0005_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'السلة', 'verbose_name_plural': '_السلل'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'عنصرالسلة', 'verbose_name_plural': '_عناصر السلة'},
        ),
    ]
