# Generated by Django 5.1.6 on 2025-03-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0006_alter_cart_options_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'السلة', 'verbose_name_plural': 'f_السلل'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'عنصر السلة', 'verbose_name_plural': 'f_عناصر السلة'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'فئة', 'verbose_name_plural': 'a_الفئات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'c_المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'صورة منتج', 'verbose_name_plural': 'd_صور المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'فئة فرعية', 'verbose_name_plural': 'b_ الفئات الفرعية'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'مفضل', 'verbose_name_plural': 'e_المفضلة'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='السعر الاجمالي'),
        ),
    ]
