# Generated by Django 5.1.6 on 2025-03-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'السلة', 'verbose_name_plural': 'f_السلال'},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
