# Generated by Django 5.1.6 on 2025-03-23 08:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0010_alter_customerbaby_baby_picture'),
        ('_product', '0009_alter_cart_options_remove_cartitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_account.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.product')),
            ],
        ),
    ]
