# Generated by Django 5.1.6 on 2025-04-14 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0010_alter_customerbaby_baby_picture'),
        ('_product', '0011_alter_review_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': ' مراجعة المنتج ', 'verbose_name_plural': 'g_مراجعات المنتجات'},
        ),
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_account.customer')),
            ],
            options={
                'verbose_name': ' الموصل  ',
                'verbose_name_plural': 'h_الموصلين',
            },
        ),
        migrations.CreateModel(
            name='OrderCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('value_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_stats', models.CharField(choices=[('p0', 'قيد الانتظار'), ('p1', 'جار المعالجة'), ('p2', 'تم الشحن'), ('p3', 'تم التسليم'), ('p4', 'تم الإلغاء')], default='p0', max_length=2)),
                ('order_stats', models.CharField(choices=[('o0', 'لم يتم التسليم'), ('o1', 'تم التسليم')], default='o0', max_length=2)),
                ('received_stats', models.CharField(choices=[('r0', 'لم يتم الاستلام'), ('r1', 'تم الاستلام')], default='r0', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='_product.delivered')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' الطلب  ',
                'verbose_name_plural': 'o_الطلبات',
            },
        ),
    ]
