# Generated by Django 5.1.6 on 2025-04-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0013_orderlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLog',
        ),
    ]
