# Generated by Django 5.1.6 on 2025-04-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0010_alter_customerbaby_baby_picture'),
        ('_product', '0014_delete_orderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckout',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='_account.customer'),
        ),
    ]
