# Generated by Django 5.1.6 on 2025-04-22 10:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0011_alter_customer_additional_phone_and_more'),
        ('_product', '0016_alter_ordercheckout_order_stats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='created_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_account.customer', verbose_name='تمت الاضافة من'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم عامل التوصيل'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='additional_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف اضافي للمنتج'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_product.cart', verbose_name='السلة'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='كود السلة المنفرد'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='_account.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='_product.delivered', verbose_name='عامل التوصيل'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='order_stats',
            field=models.CharField(choices=[('o0', 'قيد الانتظار'), ('o1', 'جار المعالجة'), ('o2', 'تم الشحن'), ('o3', 'تم التسليم'), ('o4', 'تم الإلغاء')], default='o0', max_length=2, verbose_name='حالة الشحن'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='payment_stats',
            field=models.CharField(choices=[('p0', 'لم يتم التسليم'), ('p1', 'تم التسليم')], default='p0', max_length=2, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='received_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='received_stats',
            field=models.CharField(choices=[('r0', 'لم يتم الاستلام'), ('r1', 'تم الاستلام')], default='r0', max_length=2, verbose_name='حالة الاستلام'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='قام بالتعديل:'),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='value_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_age_range',
            field=models.CharField(choices=[('a', '1-3 أشهر'), ('b', '4-6 أشهر'), ('c', '7-9 أشهر'), ('d', 'سنة')], default='a', max_length=50, verbose_name='الفئة العمرية'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_account.customer', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='_product.product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name=''),
        ),
    ]
