"""
Django settings for LM project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# [static 1]:
import os

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fgmvui5(gw8&qtm^u448ya+)g#rp$2qid98cdefw7opx@33^*1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# DEBUG = False

# ALLOWED_HOSTS = ['*']


# Application definition
AUTH_USER_MODEL = '_account.CustomUser'  
# استبدل your_app_name باسم تطبيقك

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    '_account',
    '_pages',
    '_product',
]
# Lang_ar[1]=> 'django.middleware.locale.LocaleMiddleware',  next> templat
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware', 

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LM.urls'

# Lang_ar[2]=> 'django.template.context_processors.i18n',  next> Internationalization
# [static 2]=> 'DIRS': [os.path.join(BASE_DIR, 'templates')], next> urls.py
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',

                '_product.context_processors.wishlist_product_count',
                '_product.context_processors.cartItem_product_count',
                # '_product.context_processors.single_product_coungt',
            ],
        },
    },
]

WSGI_APPLICATION = 'LM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

'''  '''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# main Localhost
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lmdb',
        'USER': 'postgres',
        'PASSWORD': '12345678reem',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}'''

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'railway',
#         'USER': 'postgres',
#         'PASSWORD': 'ImsxlndnSxKBYCOqyiJjzmBanVjbevyJ',
#         'HOST': 'maglev.proxy.rlwy.net',
#         'PORT': '35644', # 5432
#     }
# }
# postgresql://postgres:ImsxlndnSxKBYCOqyiJjzmBanVjbevyJ@maglev.proxy.rlwy.net:35644/railway


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

'''
Lang_ar[3]=> LANGUAGES = [
    ("ar", ("Arabic")),
    ("en", ("English")),
]
next> Urls.py
'''
# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", ("English")),
    ("ar", ("Arabic")),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# [static 2]:
# 1
STATIC_URL = 'staticfiles/'
# 4
STATICFILES_DIRS = [  BASE_DIR / 'staticfiles'  ]
# STATIC_ROOT =os.path.join(BASE_DIR, 'staticfiles')
# 2
MEDIA_ROOT = os.path.join(BASE_DIR, 'staticfiles/images')
# 3
MEDIA_URL = '/images/'

# Email and Login:
LOGIN_URL = 'signIn'


EMAIL_HOST= "smtp.gmail.com" #نحديد خادم الارسال 
EMAIL_PORT= 465 #تحديد المنفذ
EMAIL_USE_SSL=True # استخدامه لتشفير البريد SSL
EMAIL_HOST_USER= "reemnajeeb199900@gmail.com" # البريد الذي سيستخدمه الخادم لارسال من عبرة
EMAIL_HOST_PASSWORD= "yjti vxad uxcg ugiq" # كلمة المرور البريد الذي سيستخدمه الخادم لارسال من عبرة 


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

