# Generated by Django 5.1.6 on 2025-03-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0005_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
    ]
