# Generated by Django 5.1.6 on 2025-03-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0006_remove_customuser_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBaby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baby_name', models.CharField(max_length=255)),
                ('baby_birthday', models.DateField()),
                ('baby_gender', models.CharField(choices=[('0', 'ذكر'), ('1', 'أنثى')], max_length=1)),
                ('baby_picture', models.ImageField(blank=True, null=True, upload_to='customer_baby_pictures/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='_account.customer')),
            ],
        ),
    ]
