# Generated by Django 5.1.6 on 2025-03-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0007_customerbaby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbaby',
            options={'verbose_name': 'طفل', 'verbose_name_plural': 'اطفال'},
        ),
    ]
