# Generated by Django 5.1.6 on 2025-03-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0009_alter_customerbaby_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbaby',
            name='baby_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='customer_baby_pictures/'),
        ),
    ]
