# Generated by Django 5.1.6 on 2025-04-22 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_account', '0010_alter_customerbaby_baby_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم اضافي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_account.city', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_account.street', verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
